apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.simple" . }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: "apacheserver"
        image: {{ .Values.apache.image }}
        imagePullPolicy: Always
        env:
        - name: SERVER_MESSAGE
          value: {{ tpl .Values.apache.message . | quote }}
        ports:
        -  name: server-endpoint
           containerPort: 8000
